### ISSUE TITLE
Backend: Users registration

### ISSUE THREAD

**Issue by haythemd** [ecome-earth/MyFarm#15]
## Task

- As a User I should be able to sign up to the app and choose an initial role

## Acceptance Criteria

- [ ] User is successfully registered
- [ ] Apply common registration validation ( input / duplicates / invalid schemas )
- [ ] After successful registration, Infos should be logged into Kafka topic,
- [ ] Integrate Keycloak to manage authentication
- [ ] Create an Authority Enum with different User Roles
- [ ] Use same data model for all operations mentioned in the documentation

## Support Material

Please see documentation

## Donation 

Pending assignment

**Comment by mootezchachia** [comment]
test
