### ISSUE TITLE
Backend: ToDo

### ISSUE THREAD

**Issue by haythemd** [ecome-earth/MyFarm#17]
## Task

- As a User I should be able to add, delete, edit and view my ToDos list.

## Acceptance Criteria

- [ ] CRUD Operations,
- [ ] After successful operation, Infos should be logged into Kafka topic,
- [ ] Use same data model for all operations mentioned in the documentation,
- [ ] Only Users with Expert Role Have access to all Todos operations
- [ ] Users with Farmer role can only edit the Todo and change the isDone property

## Support Material

Please see documentation

## Donation 

Pending assignment
